INSERT INTO department(name) VALUES ('Team Avenger');
INSERT INTO department(name) VALUES ('Team Shield');
INSERT INTO department(name) VALUES ('Neutral');

INSERT INTO role(title, salary, department_id) VALUES ('Captain America', 1000000, 1);
INSERT INTO role(title, salary, department_id) VALUES ('Iron Man', 1000000, 2);
INSERT INTO role(title, salary, department_id) VALUES ('Assassin', 500000, 1);
INSERT INTO role(title, salary, department_id) VALUES ('King', 500000, 2);
INSERT INTO role(title, salary, department_id) VALUES ('Pilot', 250000, 1);
INSERT INTO role(title, salary, department_id) VALUES ('Android', 500000, 2);
INSERT INTO role(title, salary, department_id) VALUES ('Agent', 250000, 2);
INSERT INTO role(title, salary, department_id) VALUES ('Witch', 250000, 1);
INSERT INTO role(title, salary, department_id) VALUES ('Guard', 500000, 2);
INSERT INTO role(title, salary, department_id) VALUES ('Ronin', 400000, 1);
INSERT INTO role(title, salary, department_id) VALUES ('Magician', 250000, 1);
INSERT INTO role(title, salary, department_id) VALUES ('Muscle', 750000, 3);
INSERT INTO role(title, salary, department_id) VALUES ('Wizard', 1000000, 3);
INSERT INTO role(title, salary, department_id) VALUES ('Asgardian', 1000000, 3);

INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Steve', 'Rogers', 1, NULL);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Tony', 'Stark', 2, NULL);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Bucky', 'Barnes', 3, 2);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ("T'Challa", 'Udaku', 4, 1);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Sam', 'Wilson', 5, 2);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Vision', 'Jarvis', 6, 2);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Natasha', 'Romanoff', 7, 1);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Wanda', 'Maximoff', 8, 2);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('James', 'Rhodes', 9, 1);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Clint', 'Barton', 10, 2);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Scott', 'Lang', 11, 2);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Bruce', 'Banner', 12, NULL);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Steven', 'Strange', 13, NULL);
INSERT INTO employee(first_name, last_name, role_id, manager_id) VALUES ('Thor', 'Odinson', 14, NULL);